server:
  port: 9999
risk:
  tony:
    component:
      pointcut: execution(* com.tony.example..*.*(..))
      feishu:
#        webhooks: https://open.feishu.cn/open-apis/bot/v2/hook/e124fb29-8617-4716-b029-a8e5e1fde2d0
        webhooks: https://open.feishu.cn/open-apis/bot/v2/hook/975d6f93-a701-41bf-bad3-78a69fbc6e67
        kibana:
          url: https://127.0.0.1/app/kibana#/discover
          sname: xl-risk-jsticker-svc
          stype: javadaemon
