server:
  port: 9999
risk:
  tony:
    component:
      pointcut: execution(* com.tony.example..*.*(..))
      feishu:
        webhooks: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxxxxxxxx
        kibana:
          url: https://127.0.0.1/app/kibana#/discover
          sname: xl-risk-jsticker-svc
          stype: javadaemon
